name: DC_Robot
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0<3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_typeahead: 4.3.8
  
  
  http: ^0.13.4
  flutter_launcher_icons: ^0.11.0
  easy_splash_screen: ^1.0.4
  flutter_spinkit: ^5.1.0
  autocomplete_textfield: ^2.0.1
  agora_rtc_engine: ^6.1.1
  permission_handler: ^10.2.0
  get: ^4.6.5
  dropdown_button2: ^2.1.2

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/DC Ro.png"
  min_sdk_android: 
  web:
    generate: true
    image_path: "images/DC Ro.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/DC Ro.png"
    icon_size: 
  macos:
    generate: true
    image_path: "images/DC Ro.png"

flutter:

  uses-material-design: true
  assets:

    - images/